---
title: "VMM FSL tables"
author: "I S Plank"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(ggpubr)
library(ggrain)

```

## Combine FSL output

```{r table, message=FALSE}

# get one type of input from each contrast
ls.files = dir(pattern = '.*MNI-AAL.csv', path = "./results_sig")

for (file in ls.files) {
  contrast = gsub("_MNI-AAL.csv", "", file)
  type     = substr(contrast, nchar(contrast)-5, nchar(contrast)-5)
  maxima   = read_csv(file.path("results_sig", file), show_col_types = F)
  if (nrow(maxima) == 0) next
  summary  = read_delim(file.path("results_sig", 
                                  paste0(contrast, '_cluster-summary.txt')), 
                        show_col_types = F)
  output   = read_delim(file.path("results_sig", 
                                  paste0(contrast, '_randomise_output_all.txt')), 
                        show_col_types = F)
  
  relinfo  = 
    merge(
      output %>% select(`Cluster Index`, Voxels), 
      maxima %>% select(`Cluster Index`, `Value`, MNIx, MNIy, MNIz, AALname)
      ) %>%
    mutate(
      H = if_else(MNIx >= 0, "R", "L")
    ) %>%
    rename(
      `Cluster size` = "Voxels", 
      "Region" = "AALname",
      "x" = "MNIx",
      "y" = "MNIy",
      "z" = "MNIz"
    ) %>%
    arrange(desc(`Cluster Index`), desc(Value)) %>%
    relocate(`Cluster Index`, Region, `Cluster size`, H)
  colnames(relinfo)[colnames(relinfo) == "Value"] = paste0(type, "-value")
  
  write_csv(relinfo, file = file.path("results_sig", paste0(contrast, '.csv')))
  
}

```

## Hypothesis-guided ROI analysis

```{r hypo}

# COMP: same areas as Stefanics et al. (2019), Neuroimage

read_csv(file.path("results_sig", 'hgf_ctr_eps_c_ROI_fstat1.csv'), show_col_types = F) %>%
  kable(., caption = 'COMP: colour prediction error')

read_csv(file.path("results_sig", 'hgf_ctr_mu_e_ROI_fstat1.csv'), show_col_types = F) %>%
  kable(., caption = 'COMP: emotion prediction strength')

# pooled: same areas as Stefanics et al. (2019), Neuroimage

read_csv(file.path("results_sig", 'hgf_all_eps_c_ROI_fstat1.csv'), show_col_types = F) %>%
  kable(., caption = 'Pooled: colour prediction error')

read_csv(file.path("results_sig", 'hgf_all_mu_c_ROI_fstat1.csv'), show_col_types = F) %>%
  kable(., caption = 'Pooled: colour prediction strength')

read_csv(file.path("results_sig", 'hgf_all_mu_e_ROI_fstat1.csv'), show_col_types = F) %>%
  kable(., caption = 'Pooled: emotion prediction strength')

# Neural adaptation

read_csv(file.path("results_sig", 'smp_adapt_neg_ROI_tstat1.csv'), show_col_types = F) %>%
  kable(., caption = 'ALL: repetition suppression')

```

## Plotting

Plot the participants' activation in clusters larger than 100 voxels to visualise the effects. 

```{r plot}

# custom colour palette
custom.col = c("#009E73", "#D55E00", "#0058b2", "#CC79A7")

# load in the extracted activation
df.act = read_csv(file.path("fMRI_data", "grp_use-sorted.csv"), 
                  show_col_types = F) %>%
  mutate(
    diagnosis = fct_recode(diagnosis, 
                           "COMP" = "CTR")
  ) %>%
  select(diagnosis) %>%
  mutate(
    # load zstats for eps-c
    `PE colour-rFG`  = scan(file.path("fMRI_data", "eps_c_C7_meants.txt")),
    `PE colour-rSTS` = scan(file.path("fMRI_data", "eps_c_C6_meants.txt")),
    `PE colour-rINS` = scan(file.path("fMRI_data", "eps_c_C5_meants.txt")),
    `PE colour-rACC` = scan(file.path("fMRI_data", "eps_c_C4_meants.txt")),
    # load zstats for mu-z
    `PS colour-rINS`  = scan(file.path("fMRI_data", "mu_c_C3_meants.txt")),
    `PS colour-lINS`  = scan(file.path("fMRI_data", "mu_c_C4_meants.txt")),
    `PS colour-rACC`  = scan(file.path("fMRI_data", "mu_c_C5_meants.txt")),
    `PS colour-rSMG`  = scan(file.path("fMRI_data", "mu_c_C6_meants.txt")),
    `PS colour-PRC`   = scan(file.path("fMRI_data", "mu_c_C7_meants.txt")),
    # load zstats for mu-e
    `PS emotion-rPRC`  = scan(file.path("fMRI_data", "mu_e_C4_meants.txt")),
    `PS emotion-rFG`   = scan(file.path("fMRI_data", "mu_e_C3_meants.txt")),
    `PS emotion-lFG`   = scan(file.path("fMRI_data", "mu_e_C2_meants.txt")),
    # load zstat for neural adaptation
    `adaptation-rFG`  = scan(file.path("fMRI_data", "adapt_meants.txt"))
  ) %>%
  pivot_longer(cols = -diagnosis, names_to = c("parameter", "region"), 
               names_sep = "-", values_to = "activation")

# plot 
df.act %>%
  ggplot(aes(region, activation, fill = diagnosis, colour = diagnosis)) + #
  geom_rain(rain.side = 'r',
boxplot.args = list(color = "black", outlier.shape = NA, show.legend = FALSE, alpha = .8),
violin.args = list(color = "black", outlier.shape = NA, alpha = .6),
boxplot.args.pos = list(
  position = ggpp::position_dodgenudge(x = 0, width = 0.3), width = 0.3
),
point.args = list(show_guide = FALSE, alpha = .5, size = 0.5),
violin.args.pos = list(
  width = 0.6, position = position_nudge(x = 0.16)),
point.args.pos = list(position = ggpp::position_dodgenudge(x = -0.25, width = 0.1))) +
  scale_fill_manual(values = custom.col) +
  scale_color_manual(values = custom.col) +
  labs(title = "Neural correlates", x = "", y = "z-stat") + 
  facet_grid(. ~ parameter, scales = "free", space = "free") +
  geom_hline(yintercept = 0) +
  theme_bw() + 
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5), 
        legend.direction = "horizontal", 
        text = element_text(size = 12, family = "mono", face = "bold")
        )

ggsave("neural_zstat.pdf",
       units  = "mm", width  = 270, height = 100, dpi    = 300)

```