---
title: "Analysis VMM: Behavioural Data"
author: "Irene Sophia Plank"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)           # kable
library(tidyverse)       # tibble stuff
library(ggplot2)         # plots
library(ggstatsplot)     # ggplot with stats
library(ggpubr)          # background image
library(png)             # readPNG

dt.path = paste('/home/emba/Documents/EMBA', 'BVET', sep = "/")
knitr::opts_knit$set(root.dir = dt.path)

```

## R Markdown

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Behavioural data

```{r load_data, warning=F, message=F}
# load the relevant data in long format: only people with separate logs for runs
df.log1 = list.files(path = dt.path, pattern = "*task-.*\\.tsv$", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_delim(., show_col_types = F, delim = "\t"), .id = "Filename") %>%
  mutate(
    Run = sub(".*task-", "", Filename),
    Run = as.numeric(substr(Run, 1, 1))
  ) %>% filter(nchar(Subject) == 10) %>%
  select(-Filename) 
# load the relevant data in long format: only people with one log for both runs
df.log2 = list.files(path = dt.path, pattern = "*task.tsv$", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_delim(., show_col_types = F, delim = "\t"), .id = "Filename") %>%
  group_by(Subject, `Event Type`) %>%
  mutate(
    Run = case_when(`Event Type` == "Pulse" ~ row_number())
  ) %>% select(-Filename) %>% 
  ungroup() %>%
  fill(Run, .direction = "up") %>%
  mutate(
    Run = case_when(Run <= 380 ~ 1, TRUE ~ 2)
  )
# bind them together
df.log = rbind(df.log1, df.log2)

# only rows relevant for answer
df.logresp = df.log %>% 
  filter(Code != 255 & ((`Event Type` == "Response" & Code <= 4) | `flp_rel(num)` == 1)) %>%
  arrange(Subject, Run, Trial) %>%
  select(Subject, Run, Trial, `Event Type`, Time)

# find relevant responses to each flip
sub  = c()
run  = c()
trl  = c()
rt   = c()
sdt  = c()

for (i in 1:nrow(df.logresp)) {
  # first, check if this is the first row
  if (i == 1) {
    # check if it's a picture, otherwise set look for picture
    if (df.logresp$`Event Type`[i] == "Picture") {
      onset = df.logresp$Time[i] # ...get the onset and look for response
      look  = "Response"
    } else {
      look  = "Picture"
    }
  # if we are not in the first row, check if it's a new run or subject
  } else if ((df.logresp$Subject[i] != df.logresp$Subject[i-1]) | 
        (df.logresp$Run[i] != df.logresp$Run[i-1])) {
    # check if it's a picture, otherwise set look to picture
    if (df.logresp$`Event Type`[i] == "Picture") {
      onset = df.logresp$Time[i] # ...get the onset and look for response
      look  = "Response"
    } else {
      look  = "Picture"
    }
  # if it's not a new run or subject and it's a picture and we're looking for a picture...
  } else if (df.logresp$`Event Type`[i] == look & look == "Picture") {
    onset = df.logresp$Time[i] # ...get the onset and look for response
    look  = "Response"
  # if we are looking for a response and it is one...
  } else if (df.logresp$`Event Type`[i] == look & look == "Response") {
    sub   = c(sub, df.logresp$Subject[i]) # ...log it all!
    run   = c(run, df.logresp$Run[i])
    trl   = c(trl, df.logresp$Trial[i])
    rt    = c(rt, (df.logresp$Time[i] - onset)/10)
    sdt   = c(sdt, "hit")
    look  = "Picture"
  # if it's a picture and we are looking for a response
  } else if (df.logresp$`Event Type`[i] == "Picture" & look == "Response") {
    sub   = c(sub, df.logresp$Subject[i-1])
    run   = c(run, df.logresp$Run[i-1])
    trl   = c(trl, df.logresp$Trial[i-1])
    rt    = c(rt, NA)
    sdt   = c(sdt, "miss")
    onset = df.logresp$Time[i]
  # if it's a response and we are looking for a picture
  } else if (df.logresp$`Event Type`[i] == "Response" & look == "Picture") {
    sub   = c(sub, df.logresp$Subject[i-1])
    run   = c(run, df.logresp$Run[i-1])
    trl   = c(trl, df.logresp$Trial[i-1])
    rt    = c(rt, NA)
    sdt   = c(sdt, "faal")
  }
}

rt = round(rt)

df.tsk = data.frame(sub, run, trl, rt, sdt) %>%
  rename("subID" = "sub") %>%
  group_by(subID) %>%
  mutate(
    subID = as.factor(subID),
    iqr   = IQR(rt, na.rm = T),
    cl    = quantile(rt, probs = c(.75), na.rm = T) + 1.5 * iqr,
    fl    = quantile(rt, probs = c(.25), na.rm = T) - 1.5 * iqr,
    rtc   = ifelse(rt > cl | rt < fl, NA, rt),
    sdt   = as.factor(case_when(rt <= 1500 ~ sdt,
                                rt >  1500 ~ "miss", # answers slower than this are counted as misses
                                is.na(rt)  ~ sdt))
    ) %>% select(-iqr, -cl, -fl)

rm(list = c("df.log1","df.log2"))

```

```{r plot_data, warning=F, message=F}

# aggregate the data to see average reaction times and accuracies per run
df.tsk_agg = df.tsk %>%
  group_by(subID, run) %>%
  summarise(
    rt_agg = mean(rtc, na.rm = T),
    miss   = sum(sdt == "miss")/120      # there are 120 flips per run
  ) 

# how many people need to be excluded for missing too many changes in a run?
exc = df.tsk_agg %>% filter(miss > 1/3) %>% select(subID)
exc = unique(as.character(exc$subID))
print(length(exc))

# load list of pilot participant to add them to the list to be excluded
pilot = read_csv(paste0(dt.path, "/pilot-subIDs.csv"))
exc   = c(exc, pilot$subID)

# filter out from original data frame
df.tsk = df.tsk %>%
  filter(!(subID %in% exc)) # disregard runs with too many misses

# save the data frame
saveRDS(df.tsk, paste0(dt.path, "/df_VMM.RDS"))

# plot the reaction time distributions
ggplot(df.tsk, aes(x = rtc, fill = subID)) + geom_density(alpha=.3) + theme_minimal() + theme(legend.position = "none") 

# print the number of participants
length(unique(df.tsk$subID))

```
